### ISSUE TITLE
accept4: too many open files

### ISSUE THREAD

**Issue by luckyraul** [CWSpear/local-persist#20]
http: Accept error: accept unix /run/docker/plugins/local-persist.sock: accept4: too many open files; retrying in 1s
Apr  4 06:14:48 mon docker-volume-local-persist[14133]: 2016/04/04 06:14:48 http: Accept error: accept unix /run/docker/plugins/local-persist.sock: accept4: too many open files; retrying in 1s
Apr  4 06:14:49 mon docker-volume-local-persist[14133]: 2016/04/04 06:14:49 http: Accept error: accept unix /run/docker/plugins/local-persist.sock: accept4: too many open files; retrying in 1s

**Comment by CWSpear** [comment]
Not really a lot of details to work with, but I found this on StackOverflow: http://stackoverflow.com/questions/880557/socket-accept-too-many-open-files

**Comment by luckyraul** [comment]
@CWSpear  
This is not about system, this is all about your service. 

Docker, for instance, has such code in default init.d script
```
ulimit -n 1048576
if [ "$BASH" ]; then
	ulimit -u 1048576
else
	ulimit -p 1048576
fi
```

**Comment by luckyraul** [comment]
or 
```
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
```
in systemd

**Comment by CWSpear** [comment]
Again, you didn't really give me very much detail, so it's hard to tell.

What are the steps you're taking to produce this issue? Does it happen on plugin start? Does it happen when you try to start Docker containers? Does it happen when you try to create Volume with the plugin? What is the host OS where the plugin is running? Are you using any other plugins? What version of Docker are you using in the client? on the server?

Any other details you might think are relevant, it would help if it's reproducable to give me specific steps to reproduce it so I can reproduce it locally to try and debug.

**Comment by luckyraul** [comment]
docker 1.10, debian 8, kernel 4.4, no other plugins.
This happens after some hours of normal working and can be fixed only by restarting docker service.

**Comment by CWSpear** [comment]
How many volumes are you using? Are you using Docker Compose? Could you share that config?

**Comment by luckyraul** [comment]
I created just small test stand. This server is a part of swarm cluster. At start it had only 1 volume via docker compose 1.6. Then my composer project moved to another server and I wanted to remove some used volumes and docker volume ls command freezed. Then I found such every second messages  in logs.

**Comment by luckyraul** [comment]
Now It has only swarm agent and the same messages flow still is going

**Comment by rgamez** [comment]
I experienced similar errors using an older version of docker swarm which was leaking TCP sockets but note that I was NOT using local-persist, it was solved upgrading to the [swarm 1.1.3 version](https://github.com/docker/swarm/releases/tag/v1.1.3).

**Comment by luckyraul** [comment]
Anyway I suggest to add parameters to systemd

**Comment by CWSpear** [comment]
What parameters?

**Comment by luckyraul** [comment]
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

**Comment by luckyraul** [comment]
My issue still present even with latest swarm
