### ISSUE TITLE
Create the volume path using a combination of mountpoint and volume name

### ISSUE THREAD

**Issue by deviantony** [CWSpear/local-persist#25]
Hi there,

I've started to use your plugin but I've noticed something: we automatically need to create the mount point folder.

For example, using the following command:

```bash
$ docker volume create -d local-persist -o mountpoint=/data/images --name=images
```

~~I would need to ensure first that `/data/images` exists.~~

I think that would be nicer for the user if the folder was automatically created in the specified mountpoint based on the volume name. 

E.g:

```bash
# Will create /data/images
$ docker volume create -d local-persist -o mountpoint=/data/ --name=images

# Will create /data/src
$ docker volume create -d local-persist -o mountpoint=/data/ --name=src
```

What do you think about that? Would you accept a PR?

Nice job by the way !

Edit: my bad, the plugin will automatically create the mount point folder. I've decided to keep the issue open because, I think it would feel better for the user to have a volume path automatically including the volume name and simpler command line use.

**Comment by CWSpear** [comment]
Yeah, as you noted, it does create the folder for you: https://github.com/CWSpear/local-persist/blob/master/driver.go#L109-L110

As for the 2nd half, I don't like this, as it implicitly implies you could do something like:

```
# These will NOT play well together

# Will create /data/one/images
$ docker volume create -d local-persist -o mountpoint=/data/one/ --name=images

# Will create /data/two/images
$ docker volume create -d local-persist -o mountpoint=/data/two/ --name=images
```

It's a breaking change that I don't believe brings anything to the table, or at least, you haven't any strong cases for, other than "simpler command line use," which I think is trumped by the more explicit syntax providing less confusion.

Indeed, you even _lose_ something with your proposed syntax. You could no longer name the volume separate from your path if you wanted to:

```
# create volume named project-a-photos in /data/a/photos
$ docker volume create -d local-persist -o mountpoint=/data/a/photos --name=project-a-photos
```

I really appreciate your suggestion and willingness to help, but I don't think it's a change I'd be interested in incorporating.

**Comment by deviantony** [comment]
I understand :)

As for your example:

```bash
# These will NOT play well together

# Will create /data/one/images
$ docker volume create -d local-persist -o mountpoint=/data/one/ --name=images

# Will create /data/two/images
$ docker volume create -d local-persist -o mountpoint=/data/two/ --name=images
```

How could this possibly work? The volume named `images` should already be registered, thus it would be impossible to create the second volume.

**Comment by CWSpear** [comment]
@deviantony that's what I'm saying. It _won't_ work. I find the mountpoint to be the more important item here, since the name is an arbitrary label. So if we adopted the proposed syntax, how could I create a volume at `/data/one/images` and `/data/two/images`?

With the proposed syntax, you cannot. With the current syntax tho, you can (by just giving them different names).

**Comment by deviantony** [comment]
Indeed, I see the point.

Thanks for the clarification, and thanks for the plugin !
