### ISSUE TITLE
docker: Error response from daemon: Container command 'bash' not found or does not exist..

### ISSUE THREAD

**Issue by joaocc** [CWSpear/local-persist#26]
I am trying to test the local-persist volume driver, but faced the following error:
This happens on a ubuntu 16.04 configured by docker-machine.
```
$ docker run -d \
    -v /run/docker/plugins/:/run/docker/plugins/ \
    -v /var/local/docker-volume--local-persist/:/data2/ \
    cwspear/docker-local-persist-volume-plugin

$ docker volume create -d local-persist -o mountpoint=/images4 --name=images4v

$ docker volume ls
DRIVER              VOLUME NAME
local-persist       images4v

$ docker run -it --rm -v images4v:/abc ubuntu bash
docker: Error response from daemon: Container command 'bash' not found or does not exist..

$ docker run -it --rm -v imagesPlainLocal:/abc ubuntu bash
root@41f6173bb9cf:/#
```

Any ideas?
Thx

**Comment by CWSpear** [comment]
No idea. Where is `imagesPlainLocal` coming from (so I can maybe better understand why this one works)?

**Comment by joaocc** [comment]
Hi. Sorry. I should have been clearer. It was an attempt to show that a "normal" volume would work on the same image and shell combination

**Comment by CWSpear** [comment]
@joaocc If you want to use the Docker version of the plugin, you need to share the volumes you want to mount, otherwise it won't share them with the ghost. Dunno if that's the issue you're seeing here, but I was having problems recreating this issue.

**Comment by donnykurnia** [comment]
@joaocc based on my experiment using this plugin inside container, you should pass the second volume using exactly the same path:

```
$ docker run -d \
    -v /run/docker/plugins/:/run/docker/plugins/ \
    -v /var/local/docker-volume--local-persist/:/var/local/docker-volume--local-persist/ \
    cwspear/docker-local-persist-volume-plugin
```
or
```
$ docker run -d \
    -v /run/docker/plugins/:/run/docker/plugins/ \
    -v /data2/:/data2/ \
    cwspear/docker-local-persist-volume-plugin
```

Use a path that available in the docker server. This is to make sure that the mountpoint used when creating the named volume have the same path in both docker-server and inside local-persist-plugin container. Using different path will just make things more complicated when you want to set the mountpoint for the named volume.

**Comment by CWSpear** [comment]
Haven't heard from the from the original poster in a while (I know I was kinda slow to respond :-(), but I'm going to go ahead and close this. Feel free to reopen if we still think there's an issue here.

**Comment by joaocc** [comment]
Hi. Managed to have some time to test this (docker 1.11.2, ubuntu 16.04).
The error appears whenever I mount a folder that doesn't exist.
For instance: It works if I do the following:
```
$ docker run -d --name="docker-plugin-volume-local-persist" --restart="always" \
    -v "/run/docker/plugins/:/run/docker/plugins/" \
    cwspear/docker-local-persist-volume-plugin:latest

$ docker volume create -d local-persist \
    -o mountpoint=/tmp/test-persist
    --name=testvol

$ docker run --rm -it   -v testvol:/test.data   ubuntu   bash
docker: Error response from daemon: Container command 'bash' not found or does not exist..

$ mkdir /tmp/test-persist

$ docker run --rm -it   -v testvol:/test.data   ubuntu   bash
```
So I think maybe a more explicit error message would be good.
And, even better, have the plugin create the folder as per #32 :)
Cheers
