### ISSUE TITLE
v1.2.0 executable seems to have been compiled for Mac OS instead of linux

### ISSUE THREAD

**Issue by overhacked** [CWSpear/local-persist#28]
I was trying to determine why I could only get this error message out of the container:
`[dumb-init] /usr/bin/docker-volume-local-persist: Exec format error`

So I downloaded the binaries myself and checked them out:
```
$ curl -L https://github.com/CWSpear/local-persist/releases/download/v1.2.0/local-persist-linux-amd64 -o local-persist-linux-amd64-v1.2.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   598    0   598    0     0   3587      0 --:--:-- --:--:-- --:--:--  3646
100 9356k  100 9356k    0     0  2000k      0  0:00:04  0:00:04 --:--:-- 2322k

$ file local-persist-linux-amd64-v1.2.0
local-persist-linux-amd64-v1.2.0: Mach-O 64-bit x86_64 executable

$ curl -L https://github.com/CWSpear/local-persist/releases/download/v1.1.0/local-persist-linux-amd64 -o local-persist-linux-amd64-v1.1.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   598    0   598    0     0   2742      0 --:--:-- --:--:-- --:--:--  4068
100 8203k  100 8203k    0     0  2164k      0  0:00:03  0:00:03 --:--:-- 2727k

$ file local-persist-linux-amd64-v1.1.0
local-persist-linux-amd64-v1.1.0: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

Seems that the v1.2.0 binary won't execute under a Linux kernel.

**Comment by CWSpear** [comment]
Yes, my release script automates all this, but for some reason, wasn't setting the right environment and just built the Mac version!

I have fixed the release on GitHub, but for some reason, the Docker version is still giving me trouble. It now says it can't find `/usr/bin/local-persist-linux-amd64` even tho it definitely can...

**Comment by CWSpear** [comment]
And I did check that I could execute the version on GitHub on Linux. So it's not an issue with the executable itself, but something with the Docker image.

**Comment by CWSpear** [comment]
As mentioned, the binary was fixed, and I'm updating the Docker Images, too. None of the source code has changed, but did bump to `v1.2.1` just to help those that might be stuck on `v1.2.0` (I did update the `v1.2.0` image, too, tho).
