### ISSUE TITLE
Getting [dumb-init] /usr/bin/docker-volume-local-persist: No such file or directory

### ISSUE THREAD

**Issue by donnykurnia** [CWSpear/local-persist#29]
I try running plugins inside container and the container exited immidiately. Docker logs only give this single line of message:

`[dumb-init] /usr/bin/docker-volume-local-persist: No such file or directory`

```
$ docker images
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
cwspear/docker-local-persist-volume-plugin   latest              08d2b4cce1e9        15 hours ago        24.33 MB

$ docker ps -a
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS                      PORTS               NAMES
07cf4fea5594        cwspear/docker-local-persist-volume-plugin   "dumb-init /usr/bin/d"   5 seconds ago       Exited (2) 5 seconds ago                        kickass_cori

$ docker logs kickass_cori
[dumb-init] /usr/bin/docker-volume-local-persist: No such file or directory
```

**Comment by CWSpear** [comment]
Yep, this is an issue with the base image (Alpine), and there isn't an easy work around. I'm trying to investigate some solutions (see https://github.com/docker/go-plugins-helpers/issues/50). Until then, use `v1.1.0`. They are functionally the same.

**Comment by donnykurnia** [comment]
@CWSpear thanks. v1.1.0 working well.

**Comment by CWSpear** [comment]
`v1.2.0` should work now; I did also do a bump to `v1.2.1`, even tho none of the source code has changed, just to help those that might be stuck on `v1.2.0`.
