### ISSUE TITLE
Should there be both a local volume and a local-persist volume when I use this?

### ISSUE THREAD

**Issue by kelceyp** [CWSpear/local-persist#38]
Here's the script I'm using.

```
sudo docker network create -d bridge --subnet 172.25.0.0/16 my-network
sudo docker volume create -d local-persist -o mountpoint=/home/kelceyp/pgdata --name=pgdata
sudo docker volume ls
```

Output of this is as expected
```
DRIVER              VOLUME NAME
local-persist       pgdata
```

When I create a container using the volume name however

```
sudo docker run -v pgdata:/var/lib/postgresql/data/pgdata/ --net=my-network --name connie-postgres -h postgres -e POSTGRES_PASSWORD=password -e PGDATA=/var/lib/postgresql/data/pgdata -d postgres
sudo docker volume ls
```

Output of this is

```
DRIVER              VOLUME NAME
local               635a259e31a8ed38372faa7082046047f50964981244ac0ab0e0b1fb7cedf727
local-persist       pgdata
```

Which I wasn't expecting

Is there something obvious that I'm doing wrong?

Many thanks in advance.

**Comment by CWSpear** [comment]
I believe that volume is create by this line in `postgres`' `Dockerfile`: https://github.com/docker-library/postgres/blob/04b1d366d51a942b88fff6c62943f92c7c38d9b6/9.5/Dockerfile#L52

If you look at the directory created (default volumes are created on the host in `/var/lib/docker/volumes/<hash>/_data`, you can see that all there is is an empty folder `pgdata`.

So running the `postgres` image creates that volume, but then your `-v` flag overrides that, so it still exists, but isn't being used. That's what I believe is happening. Either way, pretty sure it's not related to my plugin, so I'm gonna close this.

**Comment by kelceyp** [comment]
Awesome. Thanks very much for that. I didn't think of that but I believe you are correct.
