### ISSUE TITLE
Document Go 1.5 vs. 1.6 / Bad Request: malformed Host header

### ISSUE THREAD

**Issue by wied03** [CWSpear/local-persist#39]
OS: Latest Project Atomic (CentOS 7) with Docker 1.10.3 (1.10.3-44.el7.centos is the whole version string)

I was able to get around this by compiling your code with Go 1.5. Maybe something to document/consider

```
docker volume create -d local-persist -o mountpoint=/mnt/filer_volume/gitlab/config --name=gitlab_config
Error response from daemon: create gitlab_config: create gitlab_config: Error looking up volume plugin local-persist: Plugin.Activate: 400 Bad Request: malformed Host header
```

https://github.com/emccode/rexray/issues/317

**Comment by CWSpear** [comment]
I don't get this error. I glanced through the linked issue, and it seems like it is specific with older versions of Docker?

Can you give more detail as to how to reproduce this error?

**Comment by wied03** [comment]
Sorry. I trimmed that out, put it back in.

**Comment by CWSpear** [comment]
For now, building binaries with Go 1.5: https://github.com/CWSpear/local-persist/releases/tag/v1.3.0
