### ISSUE TITLE
data migration

### ISSUE THREAD

**Issue by stephenmoloney** [CWSpear/local-persist#46]
Hi,
Just wondering if this plugin confers any benefits in terms of data backups, restoration and migration?
I wonder if it is warranted to add an example of the above 3 exercises to the readme?

**Comment by CWSpear** [comment]
I swear I responded to this...

But no, it doesn't really have any additional benefits in terms of the 3 items you mentioned above what's already mentioned in the README.

**Comment by weaktyper** [comment]
Thanks for getting back to me. Yea, that's what I thought. I'm using this local-persist at the moment. So far so good. I like having named volumes so I know whats going on and avoid dangling volumes as much as possible.
