### ISSUE TITLE
docker plugin ls

### ISSUE THREAD

**Issue by smebberson** [CWSpear/local-persist#47]
When this plugin is installed correctly, should running `docker plugin ls` produce anything related to this plugin?

**Comment by smebberson** [comment]
I'm pretty sure it didn't install correctly, because I restarted the database container (after everything was all working), and my app no longer functioned due to missing data.

Is there anyway to diagnose the install?

I received the following message after installation:

```
sudo curl -fsSL https://raw.githubusercontent.com/CWSpear/local-persist/master/scripts/install.sh | sudo bash -s --       
Stopping docker-volume-local-persist service if running

Downloading binary:
  From: https://github.com/CWSpear/local-persist/releases/download/v1.3.0/local-persist-linux-amd64
  To:   /usr/bin/docker-volume-local-persist
Binary download

Downloading Systemd service conf:
  From: https://raw.githubusercontent.com/CWSpear/local-persist/v1.3.0/init/systemd.service
  To:   /etc/systemd/system/docker-volume-local-persist.service
Systemd conf downloaded

Starting docker-volume-local-persist service...
* docker-volume-local-persist.service - docker-volume-local-persist
   Loaded: loaded (/etc/systemd/system/docker-volume-local-persist.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-02-23 15:44:33 ACDT; 29ms ago
 Main PID: 8992 (docker-volume-l)
    Tasks: 3
   Memory: 2.4M
      CPU: 5ms
   CGroup: /system.slice/docker-volume-local-persist.service
           `-8992 /usr/bin/docker-volume-local-persist

Feb 23 15:44:33 idearium-common systemd[1]: Started docker-volume-local-persist.
Feb 23 15:44:33 idearium-common docker-volume-local-persist[8992]: Starting...       Found 1 volumes on startup

Done! If you see this message, that should mean everything is installed and is running.
```

I have a feeling no output relating to this plugin from the command `docker plugin ls` doesn't really matter. Prior to installing it, I ran a `docker-compose up` and it complained about a plugin that it didn't know about. After installing it, my containers started fine...

However, the volumes are definitely not being persisted.

Any ideas?

**Comment by smebberson** [comment]
Do you know what? I'm an idiot. I had incorrectly mapped my volume, and there had two volumes to the container. The data was being written the standard Docker `local` plugin, not this one - which works perfectly :)

**Comment by CWSpear** [comment]
Glad you figured it out :-)
