### ISSUE TITLE
How to define volume size

### ISSUE THREAD

**Issue by hareemca** [CWSpear/local-persist#48]
Is there any way to one to define volume size per docker volume using this driver ?
Best Regards
Hareem Haque
Twitter: @hareemca

**Comment by CWSpear** [comment]
Docker volumes don't inherently have size. It's basically just "linking" a directory from the Docker host to a container, so it's limited by the size of your hard drive on the host.

**Comment by shyal** [comment]
hmm not being able to define the size of a volume kind of defeats the purpose of this project doesn't it?

**Comment by CWSpear** [comment]
@shyal I don't think you _understand_ the purpose of this project.

**Comment by shyal** [comment]
@CWSpear i don't?

**Comment by CWSpear** [comment]
@shyal I not really sure what to say. This plugin is about passing through your host drive/mount at a specific point. Its purpose has nothing to do with limiting the size of your said host drive/mount. That's up to you.

**Comment by shyal** [comment]
oh no, he's still up for a fight, even after i've deleted my original comments, and clearly shied away from speaking him any further..
