### ISSUE TITLE
Can this run inside boot2docker? (docker-machine)

### ISSUE THREAD

**Issue by markvillar** [CWSpear/local-persist#51]
Hi, since this plugin wouldn't run on macOS, I am wondering if it is possible to create a new docker-machine (boot2docker), ssh into it and install this plugin directly inside the vm? I am not sure if the plugin is going to persist after docker or vm gets restarted?

I am quite surprised this feature is still not implemented natively on the latest release of docker, there's still no way to have named volume with ```host/data:/container/data```.

**Comment by CWSpear** [comment]
@markvillar I don't really know if it'll work with `boot2docker`. You're kinda in uncharted territory. In theory, it could work, but I don't know how often the VM gets turned over like you mentioned, which could cause you to have to re-install it.

The other option you have that I've used in development in the past is to run the plugin itself via Docker ([see the docs](https://github.com/CWSpear/local-persist#running-from-within-a-container)) (**recommended**). I've gotten this to work with Docker for Mac in the past.

As to your last point, you can get a similar set up with docker compose config like this:

```
volumes:
  database:
    driver_opts:
      type: none
      device: /data/project/database/
      o: bind
```

I don't really know what those options do, this is just something I found in another GitHub comment. I don't know how this differs from what this plugin does (other than it wasn't possible when I figure created this plugin), except that the above requires the host path (in this example, `/data/project/database`) to already exist.

**Comment by CWSpear** [comment]
I should mention that the Docker docs said that it wasn't recommended to run plugins inside a Docker container for production (but last I checked, they didn't say _why_). But it should be fine for development.

**Comment by HaiNguyen007** [comment]
I test on debian 8, and docker 1.12.6 built-in docker volume driver: local not working:

Both in docker-compose.yml
volumes:
  database:
    driver_opts:
      type: none
      device: /data/project/database/
      o: bind

and command line is also not working:
docker volume create --driver local --opt type=none --opt device=/home/user5/nfsdata/ --opt o=bind --name test003

So local-persist driver is my choice. Thank you for great driver.
