### ISSUE TITLE
How to install on Docker for mac

### ISSUE THREAD

**Issue by pimpelsang** [CWSpear/local-persist#52]
Is it possible to have it running outside container?

I've tried running install script in new docker-machine (bash not found, sudo can't set up services), then running it inside container (Error response from daemon: Mounts denied)

Maybe some hints to readme as well?

**Comment by bilby91** [comment]
Looking for the same here. A minimal example of how to use this in Docker for Mac!

**Comment by CWSpear** [comment]
You have to use it as a container if you want to use for Docker for Mac: https://github.com/CWSpear/local-persist#running-from-within-a-container
