### ISSUE TITLE
Support and install instructions for OSX

### ISSUE THREAD

**Issue by aallbrig** [CWSpear/local-persist#55]
Hey, I do docker development on OSX and was hoping to see a guide on how to install this plugin on OSX.

Right now, the instructions...

> To create a Docker Plugin, one must create a Unix socket that Docker will look for when you use the plugin and then it listens for commands from Docker and runs the corresponding code when necessary.

... is pretty terse.  Based on this instruction, it seems that I must be an expert at both docker and unix in order to understand the practical steps to take, which seems like a high barrier for most docker noobs (myself included).  What are some example steps to accomplish this, even in your OS of choice?  Having some commands would serve as a starting point to translate OS specific commands.

Also, this plugin isn't supported for those of us running OSX?

> This needs be to run on the Docker host. i.e. *running that on a Mac won't work (and it will print a message saying as much and exit).*

- - -

I can't seem to find any guides online on how to install this plugin for OSX.  Is it indeed not possible?  Thanks!

**Comment by bool-dev** [comment]
Would be great if this was available "outside a container" (#52), so I tried to build the plugin from source, but failed!

Workaround is to just run it inside container as mentioned in the instructions. One could also set the `--restart unless-stopped` option to have it automatically start on docker start, after the first run.

**Comment by CWSpear** [comment]
It wasn't possible when I created this and I periodically checked in for a while to see if it was, but I stopped checking regularly and it's been a while. I can check again, but in the meantime, the idea is you run it from a container:

https://github.com/CWSpear/local-persist#running-from-within-a-container

I went ahead and updated that section (see [#59 (files)](https://github.com/CWSpear/local-persist/pull/59/files)) to explicitly reference "Running on Mac and Windows."

**Comment by CWSpear** [comment]
To further clarify, this will probably never work natively with Windows or Mac, because it requires communicating with the Docker daemon directly. So while I'm exploring ways to maybe make it easier, my last comment will work and is the best solution right now.
