### ISSUE TITLE
Docker for Windows support

### ISSUE THREAD

**Issue by nick4fake** [CWSpear/local-persist#58]
Is there docker for windows support planned?

Similar issue: https://github.com/CWSpear/local-persist/issues/55

**Comment by CWSpear** [comment]
It wasn't possible when I created this and I periodically checked in for a while to see if it was, but I stopped checking regularly and it's been a while. I can check again, but in the meantime, the idea is you run it from a container:

https://github.com/CWSpear/local-persist#running-from-within-a-container

I went ahead and updated that section (see [#59 (files)](https://github.com/CWSpear/local-persist/pull/59/files)) to explicitly reference "Running on Mac and Windows."

**Comment by CWSpear** [comment]
To further clarify, this will probably never work natively with Windows or Mac, because it requires communicating with the Docker daemon directly. So while I'm exploring ways to maybe make it easier, my last comment _will_ work and is the best solution right now.
