### ISSUE TITLE
issue on installing

### ISSUE THREAD

**Issue by killmasta93** [CWSpear/local-persist#99]
Hi currently trying to install on ubuntu 20.04 normally it worked before but im getting

```
curl -fsSL https://raw.githubusercontent.com/MatchbookLab/local-persist/master/scripts/install.sh | sudo bash
dirname: missing operand
Try 'dirname --help' for more information.
/

```

**Comment by nigel914** [comment]
I believe this is happening because the link is downloading the entire page instead of the "systemd.service" file itself

**Comment by nguyenleminhquan** [comment]
i also enter this issue when using install script on Ubuntu 18.04

**Comment by FriedCircuits** [comment]
I worked around this by using the previous commit, for example: https://raw.githubusercontent.com/CWSpear/local-persist/45c5c344d5dfd358c28d7148be48302d20456fac/scripts/install.sh.

In my case it might of been an issue running in Ansible and `$BASH_SOURCE` returning empty. I created a test script, ran the snippet manually, and it worked fine.

**Comment by killmasta93** [comment]
yeah that did the trick
